- name: Enable Delorean Repository
  script: ../files/enable_repositories.sh creates=/etc/yum.repos.d/delorean-deps.repo
  sudo: yes

- name: Install yum-plugin-priorities package
  yum: name=yum-plugin-priorities state=latest
  sudo: yes

- name: Install python-tripleoclient
  yum: name=python-tripleoclient state=latest
  sudo: yes

- name: Find stackrc
  stat: path=/home/stack/stackrc
  register: stackrc
  become: yes
  become_user: stack

- name: Set enable_validations in /home/stack/undercloud.conf
  ini_file: dest="/home/stack/undercloud.conf" section=DEFAULT option=enable_validations value=true backup=yes
  become: yes
  become_user: stack

- name: Install undercloud (this will take a while!)
  environment: 
    DIB_INSTALLTYPE_puppet_modules: "{{ dib_install_type_puppet_modules }}"
  shell: openstack undercloud install
  when: stackrc.stat.exists == false
  become: yes
  become_user: stack

- name: Set cors allowed_origin in /etc/keystone/keystone.conf
  ini_file: dest="/etc/keystone/keystone.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes

- name: Restart httpd
  service: name=httpd state=restarted
  sudo: yes

- name: Set cors allowed_origin in /etc/ironic/ironic.conf
  ini_file: dest="/etc/ironic/ironic.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes

- name: Set cors allow_headers in /etc/ironic/ironic.conf
  ini_file: dest="/etc/ironic/ironic.conf" section=cors option=allow_headers value=Content-Type,Cache-Control,Content-Language,Expires,Last-Modified,Pragma,X-Auth-Token
  sudo: yes

- name: Restart ironic api 
  service: name=openstack-ironic-api state=restarted
  sudo: yes
  ignore_errors: yes
  
- name: Set cors allowed_origin in /etc/heat/heat.conf
  ini_file: dest="/etc/heat/heat.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes
  
- name: Restart heat api 
  service: name=openstack-heat-api state=restarted
  sudo: yes
  
- name: Set cors allowed_origin in /etc/mistral/mistral.conf
  ini_file: dest="/etc/mistral/mistral.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes
  
- name: Restart mistral api 
  service: name=openstack-mistral-api state=restarted
  sudo: yes
  
- name: Set cors_allow_origin in /etc/swift/proxy-server.conf
  ini_file: dest="/etc/swift/proxy-server.conf" section=DEFAULT option=cors_allow_origin value=* backup=yes
  sudo: yes
  
- name: Restart swift proxy 
  service: name=openstack-swift-proxy state=restarted
  sudo: yes
